### ISSUE TITLE
Problem when creating date formatters

### ISSUE THREAD

**Issue by cufapaez** [yoomoney-tech/mobile-analytics-chart-swift#15]
After declaring the constants for 'dmmmyyyyDateFormatter' and 'dmmmDateFormatter' in the ContentView, two errors pop up from Xcode: "Expresions are not allowed at the top level".

**Comment by cufapaez** [comment]
Fixed it! Need to have property declarations on ContentView. Simply execute a closure (which returns the object we are after) and assigns it to the property. Since the expressions are hidden are inside the closure, the compiler is happy as it has a context for executing the code.

`// Creating date formatters
let dmmmyyyyDateFormatter: DateFormatter = {
    let df = DateFormatter()
    df.dateFormat = "d MMM yyyy"
    return df
}()

let dmmmDateFormatter: DateFormatter = {
    let df = DateFormatter()
    df.dateFormat = "d MMM "
    return df
}()`

**Comment by machugram** [comment]
**func dateFormat(dateFormat : String)->DateFormatter{
    let dmmmyyyyDateFormatter = DateFormatter()
    dmmmyyyyDateFormatter.dateFormat = dateFormat
    return dmmmyyyyDateFormatter
}**
The issue is closed but this is my suggestion for reusability.
A simple to use date formatter function is better
